### ISSUE TITLE
`RsWithBody` duplicates content-length header

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#305]
`RsWithBody`should add content-length header if this header is absent, do not duplicate it.

**Comment by g4s8** [comment]
@olenagerasimova I'm suggesting adding secondary constructor to `RsWithHeaders`:
```java
RsWithHeaders(Response origin, Headers headers, boolean override)
```
with `false` default value; this constructor will flag that header value needs to be replaced if already exist. And `RsWthiBody` can use this constructor with `true` flag to `content-length` replace.

Reasoning: since HTTP protocol allows to have multiple values for one header name (one-to-many relation for headers), it's the responsibility of user (protocol user = programmer) to specify where to override or not the header.

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.18.3`
